# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    authentication_handler:
        class:        AppBundle\Handler\AuthenticationHandler
        arguments:    ['@router', '@fos_user.user_manager', '@service_container']

    app.listener.registration:
        class:        AppBundle\Listener\RegistrationListener
        arguments:    ["@request_stack"]
        tags:
                    - { name: kernel.event_subscriber }